### What is numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

### Creating Numpy Arrays

#### Method-1 : np.array

In [3]:
# np.array

import numpy as np

# 1D
a = np.array([1,2,3]) # vector

print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [9]:
# 2D

b = np.array([[1,2,3],[4,5,6]]) # matrix

print(b)
print(type(b))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [12]:
# 3D

c = np.array([[[1,2],[3,4]], [[5,6],[7,8]]]) # tensor

print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [13]:
# dtype

np.array([1,2,3], dtype=float)

array([1., 2., 3.])

In [15]:
np.array([1,2,0], dtype=bool)

array([ True,  True, False])

In [16]:
np.array([1,2,0], dtype=complex)

array([1.+0.j, 2.+0.j, 0.+0.j])

#### Method-2 : np.arange

In [17]:
# np.arange

np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [19]:
# with reshape

np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [22]:
np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [23]:
np.arange(1,13).reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [24]:
np.arange(1,13).reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [25]:
np.arange(1,13).reshape(2,7)

ValueError: cannot reshape array of size 12 into shape (2,7)

In [36]:
np.arange(16).reshape(2,2,2,2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

#### Method-3 : np.ones and np.zeros

In [26]:
# np.ones and np.zeros

np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [28]:
np.ones((3,4), dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [29]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

- ones and zeros functions are used to initialize values of an array.

#### Method-4 : np.random

In [32]:
# np.random

np.random.random((3,4))

# range --> 0 - 1

array([[0.02473846, 0.12847784, 0.63322251, 0.8259135 ],
       [0.29174972, 0.60204766, 0.21316695, 0.28376826],
       [0.49344241, 0.31994969, 0.90542335, 0.13721616]])

#### Method-5 : np.linspace

In [34]:
# np.linspace

# linearly spaced

np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

#### Method-6 : np.identity

In [35]:
# np.identity

np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Array Attributes

In [4]:
a1 = np.arange(10,dtype=np.int32)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [38]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [40]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [41]:
# ndim

a1.ndim

1

In [42]:
a2.ndim

2

In [43]:
a3.ndim

3

In [44]:
# shape

a1.shape

(10,)

In [45]:
a2.shape

(3, 4)

In [46]:
a3.shape

(2, 2, 2)

In [50]:
# size --> no. of items

a1.size

10

In [51]:
a2.size

12

In [52]:
a3.size

8

In [58]:
# itemsize (in bytes)

a1.itemsize

4

In [56]:
a2.itemsize

8

In [57]:
a3.itemsize

4

In [61]:
# dtype

print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int32


### Changing Datatype

In [5]:
# astype

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [6]:
a3.dtype

dtype('int32')

In [9]:
a4 = a3.astype(np.int16)

a4

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int16)

In [10]:
a4.dtype

dtype('int16')

- we do it to save memory.

### Array Operations

In [71]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [72]:
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [79]:
# scalar operations

# arithmetic

a1 * 2
a1 + 2
a1 - 2
a1 / 2
a1 * 2
a1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [84]:
# relational

a2 > 5
a2 > 25
a2 > 15
a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [92]:
# vector operations

# arithmetic

a1 * a2
a1 + a2
a1 - a2
a1 / a2
a1 ** a2

array([[          0,           1,       16384,    14348907],
       [          0, -1564725563,  1159987200,   442181591],
       [          0,  1914644777, -1304428544,  -122979837]])

### Array Functions

In [3]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)

a1

array([[ 5., 22., 31.],
       [40., 23., 81.],
       [81., 56., 54.]])

In [4]:
# max/min/sum/prod

# 0 -> col and 1 -> row

np.max(a1)

81.0

In [5]:
np.sum(a1)

393.0

In [6]:
np.prod(a1)

62243503660800.0

In [9]:
import numpy as np

In [10]:
a1

array([[ 5., 22., 31.],
       [40., 23., 81.],
       [81., 56., 54.]])

In [12]:
# along row -> 1 or column -> 0

np.max(a1, axis=0)
np.min(a1, axis=0)
np.prod(a1, axis=0)

array([ 16200.,  28336., 135594.])

In [17]:
np.max(a1, axis=1)
np.min(a1, axis=1)
np.prod(a1, axis=1)

array([  3410.,  74520., 244944.])

In [19]:
# mean/median/std/var

np.mean(a1)
np.mean(a1, axis=0)

array([42.        , 33.66666667, 55.33333333])

In [22]:
np.median(a1)
np.std(a1)
np.var(a1)

623.5555555555555

In [23]:
# trigonomoetric functions

np.sin(a1)

array([[-0.95892427, -0.00885131, -0.40403765],
       [ 0.74511316, -0.8462204 , -0.62988799],
       [-0.62988799, -0.521551  , -0.55878905]])

In [25]:
# dot product

a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

In [26]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [27]:
a3

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [28]:
np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [29]:
# log and exponents

np.log(a1)

array([[1.60943791, 3.09104245, 3.4339872 ],
       [3.68887945, 3.13549422, 4.39444915],
       [4.39444915, 4.02535169, 3.98898405]])

In [31]:
np.exp(a1)

array([[1.48413159e+02, 3.58491285e+09, 2.90488497e+13],
       [2.35385267e+17, 9.74480345e+09, 1.50609731e+35],
       [1.50609731e+35, 2.09165950e+24, 2.83075330e+23]])

In [35]:
# round/floor/ceil

a4 = np.random.random((2,3))*100

a4

array([[53.322719  , 29.207947  , 72.4589461 ],
       [92.16876079, 10.85442155, 98.67116584]])

In [36]:
np.round(a4)

array([[53., 29., 72.],
       [92., 11., 99.]])

In [37]:
np.floor(a4)

array([[53., 29., 72.],
       [92., 10., 98.]])

In [38]:
np.ceil(a4)

array([[54., 30., 73.],
       [93., 11., 99.]])

### Indexing and Slicing

In [ ]:
# Indexing

In [41]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [42]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
a1[-1]
a1[1]

1

In [43]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [47]:
a2[1,2]

6

In [48]:
a2[2,3]

11

In [49]:
a2[1,0]

4

In [44]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [50]:
a3[1,0,1]

5

In [57]:
a3[0,1,0]

2

In [53]:
a3[0,0,0]

0

In [59]:
a3[1,1,0]

6

In [ ]:
# Slicing

In [58]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
a1[2:5]

array([2, 3, 4])

In [60]:
a1[2:5:2]

array([2, 4])

In [61]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [66]:
a2[0]

array([0, 1, 2, 3])

In [68]:
a2[0,:]

array([0, 1, 2, 3])

In [70]:
a2[:,2]

array([ 2,  6, 10])

In [65]:
a2[0:1]

array([[0, 1, 2, 3]])

In [71]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [72]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [76]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [77]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [80]:
a2[1,::3]

array([4, 7])

In [81]:
a2[:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [85]:
a3 = np.arange(27).reshape(3,3,3)

a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [90]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [91]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [92]:
a3[0][1]

array([3, 4, 5])

In [94]:
a3[0,1]
a3[0,1,:]

array([3, 4, 5])

In [95]:
a3[1,:,1]

array([10, 13, 16])

In [96]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [97]:
a3[::2, 0, ::2]

array([[ 0,  2],
       [18, 20]])

### Iterating

In [98]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [101]:
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [99]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [102]:
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [100]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [103]:
for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [104]:
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


In [105]:
for i in np.nditer(a2):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


### Reshaping

In [ ]:
# reshape

In [106]:
# transpose

a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [108]:
np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [109]:
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [111]:
# ravel

a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [112]:
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

- In python, if output is shown then the operation performed is temporary on given object, if not shown then it is permanent.

### Stacking

In [ ]:
# horizontal stacking

In [113]:
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)

In [114]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [115]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [116]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [117]:
np.hstack((a4,a5,a4,a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15,  0,  1,  2,  3,  0,  1,  2,  3,
        12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19,  4,  5,  6,  7,  4,  5,  6,  7,
        16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23,  8,  9, 10, 11,  8,  9, 10, 11,
        20, 21, 22, 23]])

In [ ]:
# Vertical stacking

In [118]:
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

### Splitting (opposite of stacking)

In [ ]:
# horizontal splitting

In [122]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [121]:
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [125]:
type(np.hsplit(a4,2))

list

In [126]:
np.hsplit(a4,3)

ValueError: array split does not result in an equal division

In [ ]:
# vertical splitting

In [127]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [129]:
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]

In [130]:
type(np.vsplit(a5,3))

list